version='3_2_1';

mcc -m G_cam_viewer.m...
    -a 'C:\Users\George\OneDrive - Imperial College London\Experiments\GCam\G_cam_v3_2_1\*.m'...
    -a 'C:\ProgramData\MATLAB\SupportPackages\R2016b\toolbox\imaq\supportpackages\gentl'...
    -a 'C:\ProgramData\MATLAB\SupportPackages\R2016b\toolbox\imaq\supportpackages\gige'...
    -a 'C:\ProgramData\MATLAB\SupportPackages\R2016b\toolbox\imaq\supportpackages\genericvideo'

movefile('G_cam_viewer.exe','G_cam_viewer_3_2_1.exe','f')
